name: CI/CD Pipeline for Model Training
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  train-and-validate:
    strategy:
      matrix:
        dataset: [big, small]
    runs-on: ubuntu-latest

steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Train model        
        run: python train.py --dataset ${{ matrix.dataset }}

      - name: Log to MLflow and expose accuracy
        id: logml
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
          run: python log_to_mlflow.py

      - name: Deploy if validation passes
        if: ${{ fromJSON(steps.logml.outputs.accuracy) >= 0.90}}
        run: |
          echo "Validation passed! Accuracy is ${{ steps.logml.outputs.accuracy }}"
          echo "Deploying model... (demo)"
      
      - name: Fail job if validation fails
        if: ${{ fromJSON(steps.logml.outputs.accuracy) < 0.90}}
        run: |
          echo "Validation failed! Accuracy is ${{ steps.logml.outputs.accuracy }}"
          exit 1
      
      - name: Upload training artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ matrix.dataset }}
          path: |
            metrics.json
            model/
